repos:
  - repo: https://github.com/rtts/djhtml
    rev: 3.0.10  # replace with the latest tag on GitHub
    hooks:
      - id: djhtml
        entry: djhtml -t 2
        files: templates/.
      - id: djcss
        types: [scss]
  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black
  - repo: https://github.com/hadialqattan/pycln
    rev: 'v2.6.0'
    hooks:
      - id: pycln
